version: "3.3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: uno2tres
    #ports:
    #  - 3306:3306
    volumes:
      - my_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    network_mode: service:db
  # ports:
  #   - 8080:8080

volumes:
  my_data: null
